### ISSUE TITLE
Keep the name consistent. ArduboyPlaytune/ArduboyPlayTune

### ISSUE THREAD

**Issue by MLXXXp** [Arduboy/ArduboyPlayTune#3]
The name used for this library should be consistent throughout. The _t_ in _tune_ should always be either upper case or lower case.

It's lower case in:
- The _.h_ and _.cpp_ file names.
- The class name.
- The heading in _README.md_
- The _library.properties_ file (although for the actual repository URL it's upper case).
- The _Playtune_ library that this one is based on.

It's upper case in:
- The repository name.
- The body of the _README.md_ file.

F.Y.I: [_Renaming a repository_](https://help.github.com/articles/renaming-a-repository/)

**Comment by joshgoebel** [comment]
I think ekem will have to do the rename.  I fixed the README>

**Comment by MLXXXp** [comment]
@rogosher, After PR #6 I think the only thing remaining that uses _ArduboyPlayTune_ instead of _ArduboyPlaytune_ is the name of the repository itself.
[_Renaming a repository_](https://help.github.com/articles/renaming-a-repository/)
